import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,advance,command,replay,replayRecord,hash,clone} from '../dist/engine.js';
import {createArena,arenaCommand,arenaReplay} from '../dist/arena.js';
import {freshProfile,battleConfig,reward,upgrade,recruit,exportSave,parseSave,validateProfile,saveProfile,loadProfile,SAVE_KEY} from '../dist/profile.js';
import {CARDS,STAGES,VERSION} from '../dist/content.js';
function cfg(stage='arrival',seed=42){const p=freshProfile();return{...battleConfig(p,stage),seed}}
function auto(s){for(let i=0;i<1900&&!s.result;i++){
 if(s.v===100&&s.fighters.length)command(s,{type:'finisher'});
 if(s.fighters.filter(f=>f.hp>0).length<2&&s.change===12)command(s,{type:'change'});
 for(let slot=0;slot<s.hand.length;slot++){const id=s.hand[slot];if(s.fighters.length>=4&&!s.fighters.some(f=>f.hp<=0)&&s.v>=40){const r=command(s,{type:'skill',slot});if(r.ok)break}else{const r=command(s,{type:'play',slot});if(r.ok)break}}
 advance(s);
 }return s}
test('all four V-Card encounters can be won from the starter deck',()=>{for(const st of STAGES.filter(s=>!s.arena)){const s=auto(createBattle(cfg(st.id)));assert.equal(s.result,'victory',`${st.id}: ${s.hp}, ${s.enemy.hp}`)}});
test('same seed and commands recreate every state and event',()=>{const s=auto(createBattle(cfg()));const r=replayRecord(s);assert.equal(hash(replay(r)),r.stateHash);assert.deepEqual(replay(r),s)});
test('partial battle save replay and continued play equal uninterrupted play',()=>{const s=createBattle(cfg());command(s,{type:'play',slot:0});advance(s,70);const restored=replay(replayRecord(s));assert.deepEqual(restored,s);advance(s,40);advance(restored,40);assert.deepEqual(restored,s)});
test('invalid input never changes battle state or RNG',()=>{const s=createBattle(cfg()),before=hash(s);assert.equal(command(s,{type:'skill',slot:0}).ok,false);assert.equal(command(s,{type:'play',slot:9}).ok,false);assert.equal(command(s,{type:'change'}).ok,false);assert.equal(hash(s),before)});
test('time advances identically in chunks or single steps',()=>{const a=createBattle(cfg()),b=clone(a);command(a,{type:'play',slot:0});command(b,{type:'play',slot:0});advance(a,130);for(let i=0;i<130;i++)advance(b);assert.deepEqual(a,b)});
test('ignored encounter ends in defeat without infinite scheduling',()=>{const s=createBattle(cfg());advance(s,2000);assert.equal(s.result,'defeat');assert.ok(s.tick<2000)});
test('chain rejection is atomic and expires on time',()=>{const s=createBattle(cfg());command(s,{type:'play',slot:0});const slot=s.hand.findIndex(id=>{const c=CARDS.find(x=>x.id===id);return c.color!==s.chain.color&&c.team!==s.chain.team});if(slot>=0){const before=hash(s);assert.equal(command(s,{type:'play',slot}).ok,false);assert.equal(hash(s),before)}advance(s,31);assert.equal(s.chain,null)});
test('full formation, finisher and Sentai Change operate on explicit resources',()=>{const s=createBattle(cfg('giant'));s.hand=CARDS.filter(c=>c.team==='gokai'&&c.rarity==='HERO').map(c=>c.id);s.pile=[];s.soul=60;for(let i=0;i<5;i++)assert.equal(command(s,{type:'play',slot:0}).ok,true);assert.equal(s.fighters.length,5);s.v=100;s.fighters[0].hp=0;command(s,{type:'finisher'});assert.ok(s.fighters[0].hp>0);s.change=12;command(s,{type:'change'});assert.equal(s.main,null);assert.equal(s.fighters.length,0)});
test('victory rewards are exactly-once across reload',()=>{const p=freshProfile(),s=auto(createBattle({...battleConfig(p,'arrival'),seed:42})),r=replayRecord(s),base=p.mana;assert.equal(reward(p,r,s.result),true);assert.equal(p.mana,base+120);const restored=parseSave(exportSave(p));assert.equal(reward(restored,r,s.result),false);assert.equal(restored.mana,p.mana)});
test('training and recruitment conserve balances and remain valid',()=>{const p=freshProfile(),id=p.deck[0];upgrade(p,id);assert.equal(p.mana,400);assert.equal(p.owned[id].level,2);const a=recruit(p);assert.ok(p.owned[a.id]);assert.equal(p.gems,50);recruit(p);assert.equal(p.gems,0);assert.throws(()=>recruit(p));validateProfile(p)});
test('save round-trip, corruption and incompatible versions',()=>{const p=freshProfile();assert.deepEqual(parseSave(exportSave(p)),p);const bad=JSON.parse(exportSave(p));bad.payload+=' ';assert.throws(()=>parseSave(JSON.stringify(bad)),/checksum/);p.rules='future';assert.throws(()=>exportSave(p),/not supported/)});
test('malformed inventory and excessive replay bounds rejected',()=>{const p=freshProfile();p.owned[p.deck[0]].level=-1;assert.throws(()=>validateProfile(p));const q=freshProfile();q.pending={version:VERSION,config:cfg(),commands:[],endTick:999999,stateHash:'x'};assert.throws(()=>validateProfile(q))});
test('classic locking applies; archive can enter any encounter',()=>{const p=freshProfile();p.mode='classic';assert.throws(()=>battleConfig(p,'crossfire'));p.mode='archive';assert.equal(battleConfig(p,'giant').stage,'giant')});
test('stored save recovery reads a valid previous backup',()=>{const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};const p=freshProfile();saveProfile(p);p.mana=250;saveProfile(p);store.set(SAVE_KEY,'invalid');const loaded=loadProfile();assert.equal(loaded.profile.mana,500);assert.match(loaded.warning,/Recovered/)});
test('Arena uses independent deterministic commands and can be won',()=>{const s=createArena(cfg('arena'));for(let i=0;i<150&&!s.result;i++){const target=s.enemies.findIndex(e=>e.hp>0),f=s.squad[s.active];arenaCommand(s,f.energy>=2?'special':'strike',target)}assert.equal(s.result,'victory');const r={config:s.config,commands:s.commands,stateHash:hash(s)};assert.deepEqual(arenaReplay(r),s)});
test('Arena rejects unaffordable special without mutating',()=>{const s=createArena(cfg('arena')),before=hash(s);assert.equal(arenaCommand(s,'special',0).ok,false);assert.equal(hash(s),before)});
